version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./awp
      dockerfile: Dockerfile
    volumes:
      - ./awp:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
