controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth:
    path: /api/login
    methods: ['POST']
api_refresh_token:
    path: /api/token/refresh

# config/routes.yaml
app_mailer_send:
    path: /mailer/send
    methods: [GET]
    controller: 'App\EventSubscriber\UserMailSubscriber::sendMail'
