name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      
      - name: Install Composer
        run: sudo apt-get install -y composer
      
      - name: Install Symfony CLI
        run: |
          wget https://get.symfony.com/cli/installer -O - | bash
          echo "$HOME/.symfony*/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          cd api
          composer install

      - name: Run api platform
        run: |
          cd api
          symfony serve -d --ansi
      
      - name: Run PHPUnit
        run: |
          cd api
          ./vendor/bin/phpunit --configuration phpunit.xml.dist
