name: CI/CD Pipeline
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build Docker image
        run: docker build -t moimathis/cesibackend:latest .
 
  test:
    runs-on: ubuntu-latest
    needs: build
 
    services:
      docker:
        image: moimathis/cesibackend:latest
        options: --health-cmd="curl --fail http://localhost:8000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 8000:8000
 
    steps:
      - name: Wait for Docker container to be healthy
        run: sleep 30
 
      - name: Run API tests
        run: |
          curl -f http://localhost:8000/api/endpoint
          # Add more curl commands or use a tool like Postman/Newman for more extensive testing
      - name: Run PHPUnit Test
        run: |
          vendor/bin/phpunit
