name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code source
        uses: actions/checkout@v2

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Choisis la version de PHP appropriée
          extensions: mbstring, xml, bcmath, intl, pdo_mysql

      - name: Installer Composer
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Configurer l'environnement
        run: |
          cp .env.example .env
          # Configure ici tes variables d'environnement si nécessaire
          echo "APP_ENV=test" >> .env

      - name: Lancer Symfony Serve
        run: |
          symfony serve --no-reload --port=8000 &

      - name: Attendre que le serveur soit disponible
        run: |
          echo "Attente que le serveur Symfony soit prêt..."
          for i in {1..30}; do
            if curl -s http://localhost:8000; then
              echo "Le serveur est prêt."
              break
            fi
            echo "En attente..."
            sleep 2
          done

      - name: Exécuter les tests PHPUnit
        run: vendor/bin/phpunit --testdox
